import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { createTheme } from "@mui/material/styles";

import "./globals.css";
import ThemeRegistry from "@/components/ThemeRegistry/ThemeRegistry";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html suppressHydrationWarning={true}>
      <body suppressHydrationWarning={true}>
        <ThemeRegistry>{children}</ThemeRegistry>
        {/* <ToastContainer /> */}
      </body>
    </html>
  );
}
